"""
Django settings for shopping_store project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False)

# ALLOWED_HOSTS configuration
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Always allow Render domain and localhost
if not ALLOWED_HOSTS or len(ALLOWED_HOSTS) == 0:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com', 'online-store-qke4.onrender.com','192.168.0.106']

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com', 'online-store-qke4.onrender.com','192.168.0.106']

INSTALLED_APPS = [
    'jazzmin',
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Cloudinary
    'cloudinary',
    'cloudinary_storage',
    # Custom apps
    'catalog',
    'orders',
    'customers',
    'cart',
    'dashboard',
]



# Channels
INSTALLED_APPS += ['channels']

# Required for Django to find the URL configuration
ROOT_URLCONF = 'shopping_store.urls'

# Required Django middleware for admin
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'customers.middleware.UserActivityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Required Django templates for admin
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_context',
                'catalog.context_processors.active_banners',
            ],
        },
    },
]

JAZZMIN_SETTINGS = {
    "site_title": "Online Store Admin",
    "site_header": "Online Store Administration",
    "site_brand": "Online Store",
    "site_logo": None,  # Set to static path for logo if available
    "welcome_sign": "Welcome to the Online Store Admin Portal",
    "copyright": "Online Store © 2025",
    "search_model": ["catalog.Product", "orders.Order", "customers.Customer"],
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": False,  # Sidebar collapsed by default
    "order_with_respect_to": ["catalog", "orders", "customers", "cart"],
    "custom_links": {
        "catalog": [{
            "name": "Product List",
            "url": "admin:catalog_product_changelist",
            "icon": "fas fa-list"
        }],
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "catalog": "fas fa-boxes",
        "orders": "fas fa-shopping-cart",
        "customers": "fas fa-user-friends",
        "cart": "fas fa-shopping-basket",
        "products.product": "fas fa-tshirt",
        "catalog.category": "fas fa-tags",
        "catalog.brand": "fas fa-copyright",
        "catalog.banner": "fas fa-image",
        "orders.order": "fas fa-receipt",
        "customers.customer": "fas fa-user",
    },
    "default_icon_parents": "fas fa-folder",  # Folder icon for app headings
    "default_icon_children": "fas fa-angle-right",  # Arrow for models
    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": True,
    "show_view_site": True,  # Show the 'View site' link in the admin
    "site_url": "/",  # Ensure the 'View site' link points to your homepage
    "custom_sidebars": {},  # Use default sidebar structure
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use DATABASE_URL if available (Render), otherwise use local PostgreSQL settings
DATABASE_URL = env('DATABASE_URL', default=None)

if DATABASE_URL:
    # Production: Use Render PostgreSQL
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL, 
            conn_max_age=600, 
            conn_health_checks=True,
            ssl_require=False  # Render handles SSL internally
        )
    }
else:
    # Local Development: Use local PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME', default='clothing_store'),
            'USER': env('DB_USER', default='postgres'),
            'PASSWORD': env('DB_PASSWORD', default='abhi'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Whitenoise configuration for serving static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Cloudinary storage for media files
if env('CLOUDINARY_URL', default=None):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': env('CLOUDINARY_URL').split('@')[-1],
        'API_KEY': env('CLOUDINARY_URL').split('//')[1].split(':')[0],
        'API_SECRET': env('CLOUDINARY_URL').split(':')[2].split('@')[0],
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = ''
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security Settings
if not DEBUG:
    # Production security settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # Development settings
    X_FRAME_OPTIONS = 'SAMEORIGIN'



# Jazzmin advanced admin UI configuration (professional light theme)
JAZZMIN_SETTINGS = {
    "site_title": "Online Store Admin",
    "site_header": "Online Store Administration",
    "site_brand": "Online Store",
    "site_logo": None,  # Set to static path for logo if available
    "welcome_sign": "Welcome to the Online Store Admin Portal",
    "copyright": "Online Store © 2025",
    "search_model": ["catalog.Product", "orders.Order", "customers.Customer"],
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["catalog", "orders", "customers", "cart"],
    "custom_links": {
        "catalog": [{
            "name": "Product List",
            "url": "admin:catalog_product_changelist",
            "icon": "fas fa-list"
        }],
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "catalog": "fas fa-boxes",
        "orders": "fas fa-shopping-cart",
        "customers": "fas fa-user-friends",
        "cart": "fas fa-shopping-basket",
        "products.product": "fas fa-tshirt",
        "catalog.category": "fas fa-tags",
        "catalog.brand": "fas fa-copyright",
        "catalog.banner": "fas fa-image",
        "orders.order": "fas fa-receipt",
        "customers.customer": "fas fa-user",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": True,
    "show_view_site": True,  # Show the 'View site' link in the admin
    "site_url": "/",  # Ensure the 'View site' link points to your homepage
}

# Jazzmin UI color theme customization (professional light)
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",  # Professional, clean light theme
    "dark_mode_theme": "",
    "navbar": "navbar-dark bg-primary",
    "sidebar": "sidebar-dark-primary",
    "accent": "accent-primary",
    "actions_sticky_top": True,
    "navbar_fixed": True,  # Make navbar fixed
    "sidebar_fixed": True,  # Make sidebar fixed
    "sidebar_expand": True,  # Make sidebar expandable
    "sidebar_collapsed": True,
}



SILKY_PYTHON_PROFILER = True

# Authentication
LOGIN_URL = 'customers:login'
LOGIN_REDIRECT_URL = 'catalog:home'
LOGOUT_REDIRECT_URL = 'catalog:home'
# Email configuration for password reset
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
# Password reset email settings
PASSWORD_RESET_SUBJECT_TEMPLATE = 'Password Reset Requested'
PASSWORD_RESET_EMAIL_TEMPLATE = 'customers/password_reset_email.html'
