# Generated by Django 6.0 on 2025-12-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
