# Generated by Django 6.0 on 2025-12-08 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('banner_type', models.CharField(choices=[('OFFER', 'Special Offer'), ('ANNOUNCEMENT', 'Announcement'), ('SALE', 'Sale'), ('INFO', 'Information')], default='INFO', max_length=20)),
                ('link_url', models.URLField(blank=True, help_text='Optional link for the banner')),
                ('link_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('background_color', models.CharField(default='#667eea', help_text='Hex color code (e.g., #667eea)', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', help_text='Hex color code (e.g., #ffffff)', max_length=7)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner/Offer',
                'verbose_name_plural': 'Banners/Offers',
                'ordering': ['-display_order', '-created_at'],
            },
        ),
    ]
