# Generated by Django 6.0 on 2025-12-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('OFFER', 'Special Offer'), ('SALE', 'Sale'), ('ANNOUNCEMENT', 'Announcement'), ('INFO', 'Information')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='banner',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Higher numbers appear first'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Leave empty for no end date', null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional link URL'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='message',
            field=models.TextField(help_text='Banner message/description'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text="Banner title (e.g., 'Weekend Sale')", max_length=200),
        ),
    ]
